version: 0.0
os: linux
files:
  - source: views/home/index.cshtml
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: authapp/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: authapp/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: authapp/scripts/stop_server
      timeout: 300
      runas: root