# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
env:
   variables:
     PROJECT: AuthApp
     DOTNET_CORE_RUNTIME: 3.1

phases:
  build:
    commands:
      - nuget restore
      - msbuild $env:AuthApp.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\${env:AuthApp}_Package\Archive\'
    base-directory: './testresults'